services:
  gestoresbbdd:
      env_file: .env
      image: ${BUILDPLATFORM}/mysql:8.1.0
      container_name: gestoresbbdd
      volumes:
        - ./mysql:/docker-entrypoint-initdb.d
        - data_bbdd:/var/lib/mysql
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - net
  adminer:
      image: ${BUILDPLATFORM}/adminer:4.8.1
      container_name: adminergestores
      depends_on:
        - gestoresbbdd
      ports:
        - "${ADMINER_PORT}:8080"
      networks:
        - net
  app:
    build:
      context: .
    user: "node"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Volumen para node_module
    ports:
      - 3000:3000
volumes:
  data_bbdd:
networks:
  net: